### ISSUE TITLE
好奇这样的抓取有意义吗?

### ISSUE THREAD

**Issue by senioi** [neoql/btlet#4]
抓取完metadata数据后,没有tracker的tr数据,这样的抓取生成的数据和magnet,有任何bt软件能下载吗?

**Comment by neoql** [comment]
@senioi 我开发这个软件的初衷是搭建自己的bt资源搜索器。所以原本没有打算加入保存种子的功能，只是将资源的相关信息和magnet link提取出来了。至于所提到的抓取生成的magnet有bt软件能下载吗，答案是有。只要你有磁力链接，没有种子也是可以进行下载的。只要客户端支持DHT协议（现在还有不支持DHT的bt客户端？），没有tracker也是可以进行下载的。

**Comment by senioi** [comment]
@neoql 如果没有原始的track信息的magnet uri,只是仅仅在DHT和公共tracker里下载,
除了迅雷这类P2P盗链加速的软件,海外正规软件基本上速度是0吧.

**Comment by senioi** [comment]
国外的大部分爬虫网站,给出的磁力链接都是带有tr参数的,只有国内所有爬虫网站都是只有一个infohash,感觉都是在为迅雷服务,走不出国门似的,我并不是否认您的工作,我只是觉得,如果不抓取原始的tracker数据去生成magnet uri,这样爬取数据意义不大,magnet uri重点是infohash,但是tracklist也是个重要参数.

**Comment by neoql** [comment]
@senioi 谢谢仁兄的建议，下下个版本应该会加入对Tracker exchange协议的支持

**Comment by senioi** [comment]
@neoql  我还以为我惹您生气了,才关了这个issues,感谢您的持续关注,
同类开源里面,也就是您这个代码写的可读性最强了,其他的都看起来不是毕设就是组装.希望btlet越来越好.star

**Comment by senioi** [comment]
@neoql 方便加个好友交流不
